version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}
    phlare_data: {}

services:
  evmos-devnet1:
    image: evmos-devnet1
    build:
      context: ./evmos-devnet
      args:
        - commit_hash=tags/v10.0.1
    restart: always
    ports:
      - 8545:8545
      - 26660:26660
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  evmos-devnet2:
    image: evmos-devnet2
    build:
      context: ./evmos-devnet
      args:
        - commit_hash=tags/v11.0.0-rc1
        - extra_flags=--metrics
    restart: always
    ports:
      - 26661:26660
      - 8546:8545
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:main
    depends_on:
      - prometheus
    ports:
      - 8000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  phlare:
    image: grafana/phlare:latest
    ports:
      - "4100:4100"
    command: -config.file=/etc/phlare/config.yaml
    volumes:
      - ./phlare/phlare.yaml:/etc/phlare/config.yaml
      - phlare_data:/data
    restart: always

  tx-bot1:
    image: facs95/tx-bot-dev
    depends_on:
      - evmos-devnet1
    environment:
      - ORCH_PRIV_KEY=0x1c384b3fb9a1cff8caee1e2d078bb9bc28a542dcc7ac779a445dc68b3dc2fe1f
      - RPC_URL=http://evmos-devnet1:8545
    restart: always

  tx-bot2:
    image: facs95/tx-bot-dev
    depends_on:
      - evmos-devnet2
    environment:
      - ORCH_PRIV_KEY=0x1c384b3fb9a1cff8caee1e2d078bb9bc28a542dcc7ac779a445dc68b3dc2fe1f
      - RPC_URL=http://evmos-devnet2:8545
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    privileged: true
    restart: always
    deploy:
      mode: global
